name: timeseries_learn_cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - matplotlib=2.2
  - numpy=1.14
  - pandas=0.23
  - pip=9.0
  - scipy=1.1
  - ipykernel=4.8
  - jupyter=1.0
  - scikit-learn=0.19
  - scipy=1.1
  - pip:
    - keras==2.1.5
    - tensorboard==1.6.0
    - tensorflow==1.6.0 # won't work unless you have a gpu
