name: timeseries_learn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - matplotlib=2.2
  - numpy=1.14
  - pandas=0.23
  - pip=9.0
  - scipy=1.1
  - ipykernel=4.8
  - jupyter=1.0
  - scikit-learn=0.19
  - scipy=1.1
  - seaborn=0.8
  - peakutils=1.2
  - pip:
    - keras==2.1.5
    - tensorflow==1.6
